### ISSUE TITLE
Design Object Specs for the Mongo DB

### ISSUE THREAD

**Issue by fbl773** [fbl773/point-b_ank#9]
# ~Task - Create The JSON specs for the DB entities that we will be putting into mongo
~"User Story": #4 
## Objective
Create Object Specs for:
* Artifact
  - Projectile Point
* Period
* Culture
* Material
* Users
* Catalogue
* Site
* Region

## Primary Entities Breakdown
![Primary_Entities_ER_Proposal drawio(1)](https://github.com/fbl773/point-b_ank/assets/32142941/36f8d325-bcc1-4e44-b9bd-d7a6a31d1272)

* **note**: "Artifact_Type" is how I propose we manage multiple artifact types _for now_. It is not the SQL way, but we are not using sql. 
* @Flake-bender - what are your thoughts on the attributes of each? I wouldn't worry about the connecting lines for right now, but as far as "things a catalogue/artifact/blah" will have how does this look?
  - note: I took the `region` field off of `Artifacts` because we can just pull it from its associated site.
  - note: I don't want to get carried away with images off the hop, we can work on adding those in next iteration

## User/System Entities Breakdown
* TODO

**Comment by fbl773** [comment]
@Martyrshot I'm on the fence about mongo... My brain is in Relational DB mode thanks to other projects... idk... It would mean a bit of nasty SQL but going from an `ORM` SQL database to a homebrew SQL database is a much smaller jump. It needs to be changed in any case. Nobody has any idea what tables exist.

**Comment by Martyrshot** [comment]
The problem I have with sticking with relational is we are still very much in the early phases of design. We don't know all of the features/fields/data that will be needed at this stage. Mongo would make our lives easier in the long run. Less conversion scripts 😅

**Comment by fbl773** [comment]
@Flake-bender pining you on this. Was hoping for an approval of the attributes for each of the entities in the image above. Look OK?

**Comment by Flake-bender** [comment]
> @Flake-bender pining you on this. Was hoping for an approval of the attributes for each of the entities in the image above. Look OK?

For points, those attributes are all fine. Technically some of those attributes are exclusively for points/knives. If we're widening the artifact category (as I think we should) then attributes like "blade-shape" or hafting-elements don't apply to, say, pieces of pottery, for example, though "culture" and dimensions still do. 

If we move some of the things around, like, move "type" closer to the top on the left side, it'll prompt people to fill that section in first, and then depending on how that is filled, it could toggle some of the other attributes on or off. 

There are some separate attributes for pottery. 

But for points that's good.

**Comment by fbl773** [comment]
Yea, I agree. I was thinking about putting all artifacts in the same table when I made this, I have since had a change of heart. A table for each artifact type seems more intuitive to me. I like where you're going with `dimensions` and `culture` though... I think I have a plan that will save us some time when we start introducing new artifact types. 

**Question**: I think it makes sense for both `sites` and `artifacts` to have a location field - should there be any difference regarding _how_ the location is collected (i.e. borden#/lat-lon/region) between the two?

**Comment by Flake-bender** [comment]
> Yea, I agree. I was thinking about putting all artifacts in the same table when I made this, I have since had a change of heart. A table for each artifact type seems more intuitive to me. I like where you're going with `dimensions` and `culture` though... I think I have a plan that will save us some time when we start introducing new artifact types.
> 
> **Question**: I think it makes sense for both `sites` and `artifacts` to have a location field - should there be any difference regarding _how_ the location is collected (i.e. borden#/lat-lon/region) between the two?

I wouldn't worry about the Borden Number system. Lat-long is sufficient for now. There is a way to generate the Alpha-part of that alphanumeric system from just the lat-long coords, but the numerical part of it depends entirely on knowing how many other sites are registered within that unit area, and that info is only really known by the Provincial Heritage Branch or maybe a couple archaeologists who have worked extensively in a given area. 

Like, as an example, FbNp-14 is the Borden Designation of the Wolf Willow Site in the creek valley at Wanuskewin. It was the 14th site registered in that area unit. I only know that because I worked there. In any random field or spot along a river bank or something, we couldn't just generate a proper Borden number, because we wouldn't know if the Heritage Branch already has some records for that area, so we wouldn't know what number to give it. We could figure out the [FbNp] part, from the Lat-long, but not the final number. And no one else, except professional archaeos knows how to figure out where FbNp is, so it's not a useful system for avocationalists or layfolk

Lat-long is best, at this point. It'll be more familiar to most users. And if we have Lat-long as the main input, we can derive the Borden designation later. 

Edit: I'll check my notes and get the chart for how to derive the Alpha-part from the lat-long. We can incorporate it, just to know what Borden Unit a site is in, it'll save a step later when the sites are formally registered with the Heritage Branch, even if we can't assign it a proper Borden number straight from the app.

**Comment by fbl773** [comment]
Closed with #24
